metadata:
  name: "peat-config-sel-force-telnet"
  description: "Example configuration of how to enforce the usage of a particular protocol for PEAT pulls from SEL relays"
  author: "cegoes"
  created: "April 7th, 2022"
  updated: ""

device_options:
  sel:
    pull_methods:
      - telnet
