# Docker has it's own release pipeline separate from workflow
# When the release workflow finishes and a release is published,
# that will trigger docker build.
#   full release: tag latest + version
#   pre-release: tag version, with "pre-"
name: Docker Build and Release

on:
  release:
    types: [published]  # released and prereleased
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0  # checkout full history
      - name: Set Tag and Build Timestamp
        id: tag_ts
        run: |
          # Get the most recent tag (by semantic version order)
          TAG=$(git describe --tags --abbrev=0)
          BUILD_TS="$(date -I'seconds')"
          echo "Latest tag is $TAG"
          echo "Build timestamp is $BUILD_TS"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
          echo "BUILD_TS=$BUILD_TS" >> "$GITHUB_OUTPUT"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f  # v5.8.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            built_by=github-actions
            org.opencontainers.image.source=${{ github.server_url}}/${{ github.repository }}
            org.opencontainers.image.created=${{ steps.tag_ts.outputs.BUILD_TS }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.tag_ts.outputs.TAG }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=,suffix=,format=short

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1  # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
        with:
          build-args: |
            PDM_BUILD_SCM_VERSION=${{ steps.tag_ts.outputs.TAG }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # TODO: dedicated builder image for caching like we did in GitLab?
          # gha cache has 10GB size limit.
          # target: builder
          # https://docs.docker.com/build/cache/backends/gha/
          cache-from: type=gha,mode=max,scope={{ github.ref }}
          cache-to: type=gha,mode=max,scope={{ github.ref }}
