name: Core Tests

on:
  release:
  push:
  pull_request:

jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit
      - name: Conventional Commits
        uses: taskmedia/action-conventional-commits@443b9cf07a7c453dfd92533a7f0d0c67fb4d8140 # v1.1.25
        with:
          types: >
            build|chore|ci|docs|feat|fix|minor|patch|perf|style|refactor|test

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true
      - name: Install dependencies
        run: pdm sync -G lint
      - name: Run Code Quality Checks
        run: |
          pdm run lint
          pdm run check-sdist --inject-junk

  # TODO: combine linux/windows into a test matrix?
  # TODO: test on osx?
  linux-unit-tests:
    name: Linux Unit Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: pdm sync -G test
      # NOTE: coverage here is limited since it's not running live tests
      - name: Run Unit Tests
        run: |
          pdm run pytest --basetemp=./pytest_files --run-slow --durations=10 --cov-report term-missing:skip-covered --cov-report html --cov-report xml --cov=peat --no-cov-on-fail --xdoctest --junitxml=linux-test-results.xml -n 8 ./tests ./peat
      - name: Upload Test Results
        uses: actions/upload-artifact@v6
        with:
          name: linux-test-results-${{ matrix.python-version }}
          path: |
            linux-test-results.xml
            htmlcov/
            pytest_files/
          if-no-files-found: error

  windows-unit-tests:
    name: Windows Unit Tests
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: pdm sync -G test
      - name: Run Unit Tests
        run: |
          pdm run pytest --basetemp=./pytest_files --run-slow --durations=10 --cov-report term-missing:skip-covered --cov-report html --cov-report xml --cov=peat --no-cov-on-fail --xdoctest --junitxml=windows-test-results.xml -vv ./tests ./peat
      - name: Upload Test Results
        uses: actions/upload-artifact@v6
        with:
          name: windows-test-results-${{ matrix.python-version }}
          path: |
            windows-test-results.xml
            htmlcov/
            pytest_files/
          if-no-files-found: error
